### ISSUE TITLE
I need help with addons

### ISSUE THREAD

**Issue by RipVanWinkle1865** [OpenNaja/cobra-tools#331]
I cannot select the addon, the box won't let me check it. Please Help.

**Comment by HENDRIX-ZT2** [comment]
Q: I install tools release zip file in blender and get this error.
A:  This error is due to the name that github gives the release and blender does not like. You either rename the zip and inside the zip to get rid of the '.' or you download master. 
![grafik](https://github.com/OpenNaja/cobra-tools/assets/28632661/cad1c984-fb6c-48da-8a2d-4737a2d241b5)
