### ISSUE TITLE
Extract as .db instead of .fdb

### ISSUE THREAD

**Issue by Kaiodenic** [OpenNaja/cobra-tools#38]
It's a minor thing, but I find regular SQL editors are easier to work with (I think .fdb uses firebird or something? I just know I can't open them with my regular editors, so I need to quickly change the extension to .db before editing). Makes small changes to mods a whole multi-step process (extract, change fdb to db, edit using SQL database viewer, change back to fdb, inject, save - easy to miss a step by accident).
Takes just a few lines across 3 files to change that:

in ``ovl_tool_gui.py:__init__:``
replace:
``supported_types = ("DDS", "PNG", "MDL2", "TXT", "FGM", "FDB", "MATCOL", "XMLCONFIG","ASSETPKG","LUA")``

with:
``supported_types = ("DDS", "PNG", "MDL2", "TXT", "FGM", "FDB","DB", "MATCOL", "XMLCONFIG","ASSETPKG","LUA")``

in ``extract.py:write_fdb():`` right after,
``name = sized_str_entry.name``

add:
```
if (name[-4:] == ".fdb"):
     name = name[:-4] + ".db"
```

in ``inject.py:inject():`` on the next line after,
``for file_path in file_paths:``

replace:
``name_ext, name, ext = split_path(file_path)``

with:
```
path_in_ovl = file_path
if (path_in_ovl[-3:] == ".db"):
	path_in_ovl = path_in_ovl[:-3] + ".fdb"

name_ext, name, ext = split_path(path_in_ovl)
```
Haven't had the chance to fully test if I missed something, but this seems to work for my JWE mod, and makes it a bit more streamlined to update.

**Comment by harlequinzeg0** [comment]
FDB files while wholly similar to mySQL .db files do have some slight differences. the header bytes are a bit different due to being different versions and the feature set has some small differences due to the opensource vs proprietary nature of the two database systems. It would be technically wrong to just change the extension. most SQL browsers can view FDB files just as easily as DB files without an extension change such as DB browser, our recommended software choice.
