### ISSUE TITLE
cobra-tools GUI not loading

### ISSUE THREAD

**Issue by TheModderMan** [OpenNaja/cobra-tools#48]
Hello, I'm having a problem when trying to use cobra-tools. I have installed everything correctly as described in the tutorial. However, when I double click on ovl_tool_gui.py python does loads it but the gui doesn't appears, so I can't open any ovl file. I also tried loading ovl_tool.bat but the same happened. As well, no pop-up window appears saying "Python 3.7.6+ x64 bit is expected!". It just stays still in the command window, as if it was trying to load the gui, but nothing happens and I don't know how to solve it. Could it be a bug of the latest version? (although I tried previous ones and the same happened). It only tells me that python 3.6.0 is being run. My operating system is Windows 10 x64, so that should not be the problem.

Here you can see what the command window shows: 
![Cobra-Tools_Command_Window](https://user-images.githubusercontent.com/64736827/80915591-99c75180-8d53-11ea-9287-25b795f1be94.JPG)

As I said, no gui appears after double clicking on ovl_tool_gui.py
Please, I wish and I would be very gratefull if you can solve me this problem. 
I look forward to hearing from you.
Thanks you so much in advance.

**Comment by HENDRIX-ZT2** [comment]
Looks like your launcher is not properly configured.
You can open a cmd in the cobra-tools folder and type:
python ovl_tool_gui.py
That should run the tool.

**Comment by AngelWarrior123** [comment]
The same thing happened to me but even if I put python ovl_tool_gui.py it does not open the tool

**Comment by TheMFArchitect** [comment]
Same here. I've more than tripped checked everything, it should be correct but it still wont open. It starts to open and then glitches for half a second and wont fully open. This is also part of the issue that I cant seem to fix:                       
" PS C:\Users\hanna> C:\Users\hanna\Desktop\cobra-tools-master\ovl_tool_gui.py
Traceback (most recent call last):
  File "C:\Users\hanna\Desktop\cobra-tools-master\ovl_tool_gui.py", line 8, in <module>
    from ovl_util.interaction import showdialog
  File "C:\Users\hanna\Desktop\cobra-tools-master\ovl_util\interaction.py", line 1, in <module>
    from PyQt5 import QtWidgets
ModuleNotFoundError: No module named 'PyQt5' 
PS C:\Users\hanna> pip install PyQt5
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: PyQt5 in c:\program files (x86)\python36-32\lib\site-packages (5.15.4)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in c:\program files (x86)\python36-32\lib\site-packages (from PyQt5) (12.9.0)
Requirement already satisfied: PyQt5-Qt5>=5.15 in c:\program files (x86)\python36-32\lib\site-packages (from PyQt5) (5.15.2) "

**Comment by HENDRIX-ZT2** [comment]
Make sure you use a current version of python, like 3.9. Then pip will work and everything else as well.

**Comment by TheMFArchitect** [comment]
Thank you so much! It works now!

**Comment by Abztec** [comment]
i m facing also facing the same problem, whenever i open the ovl_tool_gui it says:
Traceback (most recent call last):
  File "E:\Games setup\Jurassic world evolution\mods\cobra-tools-master\ovl_tool_gui.py", line 10, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

after this it automatically closes and the tool doesn't open ,
i have already installed files required with the correct version, plz help.

**Comment by HENDRIX-ZT2** [comment]
You are not following the installation instructions.

**Comment by Abztec** [comment]
But I did everything exactly as mentioned

**Comment by HENDRIX-ZT2** [comment]
No.

**Comment by Abztec** [comment]
Can you plz tell the full process once again?
